@startuml

class Point
{
    + Point(int x, int y, int a, int b);
    + Point(std::optional<int> x, std::optional<int> y, int a, int b);
    + ~Point() = default;

    + operator==(lhs : const Point&, rhs : const Point&) : bool
    + operator!=(lhs : const Point&, rhs : const Point&) : bool
    + operator+(lhs : const Point&, rhs : const Point&) : Point
    + operator<<(os : std::ostream&, element : const Point&) : ostream&

    + X : optional<int>
    + Y : optional<int>
    + A : int
    + B : int

    # operator==(lhs : const optional<int>&, rhs : const optional<int>&) : bool
    # operator!=(lhs : const optional<int>&, rhs : const optional<int>&) : bool
}

@enduml
