@startuml

class Point<class T>
{
    + Point(T x, T y, T a, T b);
    + Point(std::optional<T> x, std::optional<T> y, T a, T b);
    + ~Point() = default;

    + operator==(lhs : const Point&, rhs : const Point&) : bool
    + operator!=(lhs : const Point&, rhs : const Point&) : bool
    + operator+(lhs : const Point&, rhs : const Point&) : Point
    + operator<<(os : std::ostream&, element : const Point&) : ostream&

    + X : optional<T>
    + Y : optional<T>
    + A : T
    + B : T

    # operator==(lhs : const optional<T>&, rhs : const optional<T>&) : bool
    # operator!=(lhs : const optional<T>&, rhs : const optional<T>&) : bool
}

@enduml
