import os 

Import(['env'])

subdirs = [
    'crypto',
    'uint256',
]

for subdir in subdirs:
    script = os.path.join('src/' + subdir, 'SConscript')
    build_dir = os.path.join(str(env['BTC_BUILD']), 'bitcoin', subdir)
    SConscript(script, variant_dir=build_dir, duplicate=False)

## Aliases
env.Alias('lib',
    [
        # 'crypto-lib',
        'uint256-lib',
    ]
)

env.Alias('install-lib',
    [
        # 'install-crypto-lib',
        'install-uint256-lib',
    ]
)

env.Alias('test-lib',
    [
        'test-crypto-lib',
        'test-uint256-lib',
    ]
)

env.Alias('runtests-lib',
    [
        'runtest-crypto-lib',
        'runtest-uint256-lib',
    ]
)
